SumoLogic-Labs/sumobot

src/main/scala/com/sumologic/sumobot/core/Receptionist.scala, src/test/scala/com/sumologic/sumobot/core/ReceptionistTest.scala
(which is a workaround around strange behavior observed in the Slack API).
=> Preventing old messages from being processed

pom.xml, src/main/scala/com/sumologic/sumobot/core/Bootstrap.scala, src/main/scala/com/sumologic/sumobot/core/Receptionist.scala, src/main/scala/com/sumologic/sumobot/plugins/advice/Advice.scala, src/main/scala/com/sumologic/sumobot/plugins/chuck/ChuckNorris.scala, src/test/scala/com/sumologic/sumobot/core/ReceptionistTest.scala, src/test/scala/com/sumologic/sumobot/plugins/chuck/ChuckNorrisTest.scala
Upgrading `scala-slack-client` library to 2.2 due to the following error: https://github.com/gilbertw1/slack-scala-client/issues/43
= e.g.
```
[sumobot-akka.actor.default-dispatcher-11] [akka://sumobot/user/$a] [SlackRtmClient] Error reading event: {"type":"desktop_notification"
[...]
play.api.libs.json.JsResultException: JsResultException(errors:List((,List(ValidationError(List(Invalid type property: {}),WrappedArray(desktop_notification))))))
```
Confirmed the Sumobot works after the upgrade by manually running it with simple included plugins like help, Chuck Norris or braindump
=> Goledzki scala upgrade client to 2.2

pom.xml, src/main/scala/com/sumologic/sumobot/core/Receptionist.scala, src/main/scala/com/sumologic/sumobot/core/model/Messages.scala, src/main/scala/com/sumologic/sumobot/plugins/BotPlugin.scala, src/main/scala/com/sumologic/sumobot/plugins/OperatorLimits.scala, src/main/scala/com/sumologic/sumobot/plugins/advice/Advice.scala, src/main/scala/com/sumologic/sumobot/plugins/alias/Alias.scala, src/main/scala/com/sumologic/sumobot/plugins/awssupport/AWSSupport.scala, src/main/scala/com/sumologic/sumobot/plugins/beer/Beer.scala, src/main/scala/com/sumologic/sumobot/plugins/brain/BrainSurgery.scala, src/main/scala/com/sumologic/sumobot/plugins/chuck/ChuckNorris.scala, src/main/scala/com/sumologic/sumobot/plugins/conversations/Conversations.scala, src/main/scala/com/sumologic/sumobot/plugins/help/Help.scala, src/main/scala/com/sumologic/sumobot/plugins/jenkins/Jenkins.scala, src/main/scala/com/sumologic/sumobot/plugins/jira/Jira.scala, src/main/scala/com/sumologic/sumobot/plugins/pagerduty/PagerDuty.scala, src/main/scala/com/sumologic/sumobot/plugins/system/System.scala, src/main/scala/com/sumologic/sumobot/plugins/tts/TextToSpeech.scala, src/main/scala/com/sumologic/sumobot/test/BotPluginTestKit.scala, src/test/scala/com/sumologic/sumobot/plugins/help/HelpTest.scala
- Introducing ability to read messages from bots, not only form users.
- Moreover, using the fork of the upstream `slack-sumo-client`, adding the ability to retrieve attachments of the messages the bot send: `UserSender` vs. `BotSender`
- Adding the ability to send images
=> Accepting bot messages with attachments, sending images

src/main/scala/com/sumologic/sumobot/core/Receptionist.scala, src/main/scala/com/sumologic/sumobot/core/model/Messages.scala, src/main/scala/com/sumologic/sumobot/plugins/BotPlugin.scala, src/main/scala/com/sumologic/sumobot/plugins/advice/Advice.scala, src/main/scala/com/sumologic/sumobot/plugins/alias/Alias.scala, src/main/scala/com/sumologic/sumobot/plugins/awssupport/AWSSupport.scala, src/main/scala/com/sumologic/sumobot/plugins/beer/Beer.scala, src/main/scala/com/sumologic/sumobot/plugins/brain/BrainSurgery.scala, src/main/scala/com/sumologic/sumobot/plugins/chuck/ChuckNorris.scala, src/main/scala/com/sumologic/sumobot/plugins/conversations/Conversations.scala, src/main/scala/com/sumologic/sumobot/plugins/help/Help.scala, src/main/scala/com/sumologic/sumobot/plugins/jenkins/Jenkins.scala, src/main/scala/com/sumologic/sumobot/plugins/pagerduty/PagerDuty.scala, src/main/scala/com/sumologic/sumobot/plugins/system/System.scala, src/main/scala/com/sumologic/sumobot/plugins/tts/TextToSpeech.scala, src/main/scala/com/sumologic/sumobot/test/BotPluginTestKit.scala, src/test/scala/com/sumologic/sumobot/plugins/help/HelpTest.scala
* We were to failing to read threads earlier because threads message come with thread timeStamp. Added parentTimeStamp as optional to overcome this.
* Other changes are small formatting which I found on the fly
Fix is created by [mridul](https://github.com/mridulv) and it worked very well for us when we were reading threads messages for hackathon project.
=> Read timeStamp of parent which is sent in case of slack threads

src/main/scala/com/sumologic/sumobot/core/Receptionist.scala, src/main/scala/com/sumologic/sumobot/core/model/Messages.scala
so that we have the fancy "... is typing" indication when bot is calculating its response.
=> Introducing ResponseInProgress()

src/main/scala/com/sumologic/sumobot/core/Receptionist.scala
Making Receptionist handle message-changed events better. Some of them don't have a user specified and they are irrelevant for us in practice.
=> Fixing handling empty user in message edits

src/main/scala/com/sumologic/sumobot/plugins/BotPlugin.scala
When responding to a message in thread, we should set threadTs as the parent ts.
=> Fix responding to a message in thread in the same thread

pom.xml
Upgrading Play, otherwise executions fail with:
```
Caused by: java.lang.NoSuchMethodError: play.api.libs.json.JsonConfiguration.optionHandlers()Lplay/api/libs/json/OptionHandlers;
```
=> Upgrading Play to 2.7.1 for version compatibility

.travis.yml, README.md, config/sumobot.conf.example, pom.xml, src/main/resources/com/sumologic/sumobot/http_frontend/index.html, src/main/resources/com/sumologic/sumobot/http_frontend/index.ssp, src/main/resources/com/sumologic/sumobot/http_frontend/script.js, src/main/resources/com/sumologic/sumobot/http_frontend/style.css, src/main/scala/com/sumologic/sumobot/core/Bootstrap.scala, src/main/scala/com/sumologic/sumobot/http_frontend/DynamicResource.scala, src/main/scala/com/sumologic/sumobot/http_frontend/RoutingHelper.scala, src/main/scala/com/sumologic/sumobot/http_frontend/SumoBotHttpServer.scala, src/main/scala/com/sumologic/sumobot/http_frontend/SumoBotHttpServerOptions.scala, src/main/scala/com/sumologic/sumobot/http_frontend/authentication/AlbJwtAuthentication.scala, src/main/scala/com/sumologic/sumobot/http_frontend/authentication/BasicAuthentication.scala, src/main/scala/com/sumologic/sumobot/http_frontend/authentication/HttpAuthentication.scala, src/main/scala/com/sumologic/sumobot/http_frontend/authentication/NoAuthentication.scala, src/test/scala/com/sumologic/sumobot/http_frontend/RoutingHelperTest.scala, src/test/scala/com/sumologic/sumobot/http_frontend/SumoBotHttpServerOptionsTest.scala, src/test/scala/com/sumologic/sumobot/http_frontend/SumoBotHttpServerTest.scala, src/test/scala/com/sumologic/sumobot/http_frontend/authentication/AuthenticatedServerTest.scala, src/test/scala/com/sumologic/sumobot/http_frontend/authentication/BasicAuthenticationTest.scala, src/test/scala/com/sumologic/sumobot/http_frontend/authentication/NoAuthenticationTest.scala
- Added pluggable authentication system (optional in config):
- No authentication (default)
- Basic HTTP Auth (username + password)
- AWS ALB OpenID authentication
Example:
```
```
- Added CORS support (Access-Control-Allow-Origin header)
- Implemented HEAD, OPTIONS methods
- Added ability to disable frontends (`enabled = false`) while maintaining backwards compatibility with previous config format:
```
http {
enabled = false
host = "localhost"
port = 80
}
```
- Added page customization config (optional):
```
```
- `scalate`: for dynamic page templates - manual page generation would be cumbersome, library jar is only ~1MB
- `jwt-play`: for parsing JWT token in AWS ALB OpenID authentication
=> sumobot-over-HTTP: Authentication system

CHANGELOG.md, README.md, build.gradle, gradle.properties, pom.xml, settings.gradle
This branch: 
1. Contains changes that allow releasing artifacts targeted for specified Scala versions.
2. Migrates to Gradle as a new default build / release tool.
After merging this branch I can publicly release new versions: `sumobot_2.11:1.0.3` and `sumobot_2.12:1.0.3`
- updated Gradle configuration for building
- appended Scala suffix to artifact id (ex. `sumobot_2.12`)
- provided a to mechanism manage Scala versions (`defaultScalaVersion`, `supportedScalaVersions`)
- configured Gradle artifact signing and releasing to nexus
- updated `README.md`
- `gradlew build`
- `gradlew build -PscalaVersion=2.11.12`
- `gradlew build -PscalaVersion=2.12.8`
- `gradlew publish`
=> Support for multiple Scala versions + gradle releasing

build.gradle
So that one can run:
```
./gradlew dependencyUpdates
Picked up _JAVA_OPTIONS: -Djava.awt.headless=true
Scala version: 2.12.12
Configuration on demand is an incubating feature.
> Task :dependencyUpdates
------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------
The following dependencies are using the latest milestone version:
- com.github.ben-manes:gradle-versions-plugin:0.38.0
- com.github.slack-scala-client:slack-scala-client_2.12:0.2.14
- com.offbytwo.jenkins:jenkins-client:0.3.8
- gradle.plugin.com.hierynomus.gradle.plugins:license-gradle-plugin:0.15.0
- org.quartz-scheduler:quartz:2.3.2
- org.scalatra.scalate:scalate-core_2.12:1.9.6
The following dependencies have …
```
=> Employing ben-manes:gradle-versions-plugin

src/main/scala/com/sumologic/sumobot/core/Bootstrap.scala
**What**: now people can use `${SYNTAX}` in the `config/sumobot.conf` to refer to variables - e.g. system environment variables.
**Why**: I need it for my company's k8s framework as it requires all credentials to be passed via environment variables
We are using lightbend/config here, but not the full solution, but a partial method of `parseFile`. The default lightbend/config does the resolution by itself.
**Testing performed**: I ran the modified sumobot with a config having the variables and the values were resolved. Without it, the error message was:
```
Exception in thread "main" com.typesafe.config.ConfigException$NotResolved: need to Config#resolve() each config before using it, see the API docs for Config#resolve()
at com.typesafe.config.impl.SimpleConfig.checkValid(SimpleConfig.java …
```
=> resolve() added

src/main/scala/com/sumologic/sumobot/core/Receptionist.scala
Fixing the following error message:
```
[ERROR] [08/17/2021 02:02:56.382] [sumobot-akka.actor.default-dispatcher-17] [akka://sumobot/user/receptionist] None.get
java.util.NoSuchElementException: None.get
at scala.None$.get(Option.scala:627)
at scala.None$.get(Option.scala:626)
at com.sumologic.sumobot.core.Receptionist$$anonfun$receive$1.applyOrElse(Receptionist.scala:119)
```
It's likely this shows up when a sumobot sees a message by another sumobot (or itself).
The bug has been introduced in https://github.com/SumoLogic/sumobot/pull/86/files#diff-66b6346dd597c15e00911a366c3ea76e9dc6d893eb2bed8e891bb8b1f611a36bR119
=> Fixing empty sender NullPointerException

src/main/scala/com/sumologic/sumobot/core/Receptionist.scala, src/main/scala/com/sumologic/sumobot/core/model/Messages.scala
**Why**: the newest incarnation of the Pagerduty -> Slack migration seems to send the human readable text in `title`, not in `text`.
**What**: adding the `title` field to the `IncomingMessageAttachment`
=> Support for attachment titles

README.md, build.gradle, gradle.properties
Upgrading to https://github.com/slack-scala-client/slack-scala-client/releases/tag/v0.3.0
... which triggers removal of Scala 2.11 support, which I think we don't need anymore.
There are 3 akka-http warnings now, ignoring them for now. To be solved later :/
=> Upgrading to slack-scala-client 0.3.0 and dropping Scala 2.11

build.gradle, gradle.properties
- Moving the variables declaring dependency versions to `build.gradle` as this is where @dependabot is able to pick them up from. See https://www.sameerkulkarni.de/posts/dependabot-with-gradle/ and https://github.com/dependabot/dependabot-core/issues/1618#issuecomment-674770068
- Removing Guava as this doesn't seem to be used
=> Moving dependency versions to build.gradle, also cleaning some up

build.gradle
Reverts SumoLogic-Labs/sumobot#95
because it causes:
```
* Where:
Build file '/Users/myuser/git/bot-sumobot/build.gradle' line: 31
* What went wrong:
A problem occurred evaluating root project 'sumobot'.
> java.lang.AbstractMethodError (no error message)
```
=> Revert "Bump license-gradle-plugin from 0.15.0 to 0.16.1"

src/main/scala/com/sumologic/sumobot/plugins/alias/Alias.scala
The incoming message `show known aliases` has no parameters.
It must've been some mechanical code fix which introduced the bug.
=> Fixing `show known aliases`

build.gradle
**What**:
Removing the Ben Names Versions Gradle plugin
**Why**:
I don't think we use that any more. We are happy with @Dependabot
=> Removing ben names versions plugin

src/main/scala/com/sumologic/sumobot/brain/S3Brain.scala
**What**:
Minor refactoring.
Avoid the usage of `putAll` method.
**Why**:
To avoid the compilation error:
```
src/main/scala/com/sumologic/sumobot/brain/S3Brain.scala:82:11: ambiguous reference to overloaded definition,
both method putAll in class Properties of type (x$1: java.util.Map[_, _])Unit
and  method putAll in class Hashtable of type (x$1: java.util.Map[_ <: Object, _ <: Object])Unit
match argument types (java.util.Map[String,String])
one error found
```
using some Java versions.
Context: https://github.com/scala/bug/issues/10418
=> Remove putAll usage

build.gradle
**What**:
Removing excessive Scala lang dependencies
**Why**:
They were flagged when I tried to migrate to Scala 3 locally.
It seems like we don't need them in Scala 2 either.
=> Removing excessive dependencies for Scala

build.gradle
**What**:
Upgrading to Scalate 1.10.1
**Why**:
It's the version that supports Scala 3, so we'll need it eventually.
=> Scalate 1.10.1

build.gradle, src/main/scala/com/sumologic/sumobot/core/Bootstrap.scala, src/main/scala/com/sumologic/sumobot/core/EventsClient.scala, src/main/scala/com/sumologic/sumobot/core/HttpReceptionist.scala, src/main/scala/com/sumologic/sumobot/core/Receptionist.scala, src/main/scala/com/sumologic/sumobot/core/model/Channels.scala, src/main/scala/com/sumologic/sumobot/plugins/BotPlugin.scala, src/test/scala/com/sumologic/sumobot/core/ReceptionistTest.scala, src/test/scala/com/sumologic/sumobot/plugins/BotPluginTest.scala, src/test/scala/com/sumologic/sumobot/plugins/advice/AdviceTest.scala, src/test/scala/com/sumologic/sumobot/plugins/alias/AliasTest.scala, src/test/scala/com/sumologic/sumobot/plugins/help/HelpTest.scala
**What?**
SumoBot Start using EventsAPI as RTM Client is deprecated.
**Why?**
RTM Client is deprecated, classic bots stop working March 31st. New apps don't support RTM Client.
=> SumoBot Start using EventsAPI as RTM Client is deprecated
