.gitignore
config/sumobot.conf.example
pom.xml
src/main/resources/reference.conf
src/main/scala/com/sumologic/sumobot/core/Bootstrap.scala
src/main/scala/com/sumologic/sumobot/core/aws/AWSAccounts.scala
src/main/scala/com/sumologic/sumobot/core/config/ListOfConfigs.scala
src/main/scala/com/sumologic/sumobot/plugins/DefaultPlugins.scala
src/main/scala/com/sumologic/sumobot/plugins/OperatorLimits.scala
src/main/scala/com/sumologic/sumobot/plugins/PluginCollection.scala
src/main/scala/com/sumologic/sumobot/plugins/jenkins/Jenkins.scala
src/main/scala/com/sumologic/sumobot/plugins/jenkins/JenkinsConfigurations.scala
src/main/scala/com/sumologic/sumobot/plugins/jenkins/JenkinsJobClient.scala
src/main/scala/com/sumologic/sumobot/plugins/pagerduty/PagerDutySchedulesManager.scala
src/main/scala/com/sumologic/sumobot/plugins/pagerduty/PagerDutySettings.scala
src/test/scala/com/sumologic/sumobot/brain/S3BrainTest.scala
src/test/scala/com/sumologic/sumobot/core/aws/AWSAccountsTest.scala
src/test/scala/com/sumologic/sumobot/plugins/jenkins/JenkinsConfigurationsTest.scala

Switches from Archaius to the native Typesafe config library.

Akka config refactor

---

src/main/scala/com/sumologic/sumobot/plugins/pagerduty/PagerDutySchedulesManager.scala

https://developer.pagerduty.com/documentation/rest/escalation_policies/on_call
The API is paginated, meaning they only return 100 results at a time.  This will iterate over all the pages and return all the results instead of just the first page.

Pull in all pages of escalation policies instead of just the first page

---

.travis.yml
pom.xml
src/main/scala/com/sumologic/sumobot/core/Bootstrap.scala
src/main/scala/com/sumologic/sumobot/core/Receptionist.scala
src/main/scala/com/sumologic/sumobot/test/BotPluginTestKit.scala
src/test/scala/com/sumologic/sumobot/core/ReceptionistTest.scala
src/test/scala/com/sumologic/sumobot/core/model/ChannelTest.scala

Upgrading to the 0.1.8 version of the slack client, will upgrade to the 0.2 series in a future change.

Upgrading to latest client code.

---

src/main/scala/com/sumologic/sumobot/plugins/pagerduty/PagerDuty.scala
src/main/scala/com/sumologic/sumobot/plugins/pagerduty/PagerDutyModel.scala
src/main/scala/com/sumologic/sumobot/plugins/pagerduty/PagerDutySchedulesManager.scala

Updating Pagerduty incident API to V2 and removing V1.

Updating Pagerduty incident API to V2

---

pom.xml
src/main/scala/com/sumologic/sumobot/core/Receptionist.scala
src/main/scala/com/sumologic/sumobot/core/model/Messages.scala
src/main/scala/com/sumologic/sumobot/plugins/BotPlugin.scala
src/main/scala/com/sumologic/sumobot/plugins/OperatorLimits.scala
src/main/scala/com/sumologic/sumobot/plugins/advice/Advice.scala
src/main/scala/com/sumologic/sumobot/plugins/alias/Alias.scala
src/main/scala/com/sumologic/sumobot/plugins/awssupport/AWSSupport.scala
src/main/scala/com/sumologic/sumobot/plugins/beer/Beer.scala
src/main/scala/com/sumologic/sumobot/plugins/brain/BrainSurgery.scala
src/main/scala/com/sumologic/sumobot/plugins/chuck/ChuckNorris.scala
src/main/scala/com/sumologic/sumobot/plugins/conversations/Conversations.scala
src/main/scala/com/sumologic/sumobot/plugins/help/Help.scala
src/main/scala/com/sumologic/sumobot/plugins/jenkins/Jenkins.scala
src/main/scala/com/sumologic/sumobot/plugins/pagerduty/PagerDuty.scala
src/main/scala/com/sumologic/sumobot/plugins/system/System.scala
src/main/scala/com/sumologic/sumobot/plugins/tts/TextToSpeech.scala
src/main/scala/com/sumologic/sumobot/test/BotPluginTestKit.scala
src/test/scala/com/sumologic/sumobot/core/ReceptionistTest.scala
src/test/scala/com/sumologic/sumobot/plugins/help/HelpTest.scala

Manual merge (cherry-pick) of recent changes to `master`. Skipping the `Jira` plugin.

Merge from `stefan-jira-plugin`

---

src/main/scala/com/sumologic/sumobot/core/Receptionist.scala
src/main/scala/com/sumologic/sumobot/core/model/Messages.scala

Adding the option to send a text (comment) together with an image.

SUMO-88704: Adding `comment` field to OutgoingImage

---

src/main/scala/com/sumologic/sumobot/core/Receptionist.scala
src/main/scala/com/sumologic/sumobot/core/model/Messages.scala
src/main/scala/com/sumologic/sumobot/plugins/BotPlugin.scala
src/main/scala/com/sumologic/sumobot/plugins/advice/Advice.scala
src/main/scala/com/sumologic/sumobot/plugins/alias/Alias.scala
src/main/scala/com/sumologic/sumobot/plugins/awssupport/AWSSupport.scala
src/main/scala/com/sumologic/sumobot/plugins/beer/Beer.scala
src/main/scala/com/sumologic/sumobot/plugins/brain/BrainSurgery.scala
src/main/scala/com/sumologic/sumobot/plugins/chuck/ChuckNorris.scala
src/main/scala/com/sumologic/sumobot/plugins/conversations/Conversations.scala
src/main/scala/com/sumologic/sumobot/plugins/help/Help.scala
src/main/scala/com/sumologic/sumobot/plugins/jenkins/Jenkins.scala
src/main/scala/com/sumologic/sumobot/plugins/pagerduty/PagerDuty.scala
src/main/scala/com/sumologic/sumobot/plugins/system/System.scala
src/main/scala/com/sumologic/sumobot/plugins/tts/TextToSpeech.scala
src/main/scala/com/sumologic/sumobot/test/BotPluginTestKit.scala
src/test/scala/com/sumologic/sumobot/plugins/help/HelpTest.scala

Adding `idTimestamp` field to `IncomingMessage`, so that the (incoming) messages can be uniquely identified.

Adding idTimestamp field to IncomingMessage

---

src/main/scala/com/sumologic/sumobot/core/Receptionist.scala
src/main/scala/com/sumologic/sumobot/core/model/Messages.scala
src/main/scala/com/sumologic/sumobot/plugins/BotPlugin.scala

Adding support to send/reply-to messages in Slack threads.

Adding support for threadTs in OutgoingMessages

---

pom.xml
src/main/scala/com/sumologic/sumobot/core/Receptionist.scala
src/main/scala/com/sumologic/sumobot/core/model/Messages.scala

Upgrading to 0.2.4 of `slack-scala-client`

Upgrading to 0.2.4

---

pom.xml
src/main/scala/com/sumologic/sumobot/brain/S3Brain.scala
src/main/scala/com/sumologic/sumobot/plugins/awssupport/AWSSupport.scala
src/test/scala/com/sumologic/sumobot/brain/S3BrainTest.scala

Mechanical upgrade of the dependency.

Upgrading AWS SDK dependency

---

pom.xml
src/main/scala/com/sumologic/sumobot/core/Receptionist.scala
src/test/scala/com/sumologic/sumobot/core/ReceptionistTest.scala
src/test/scala/com/sumologic/sumobot/core/model/ChannelTest.scala

Upgrading to 0.2.5

---

pom.xml
src/main/scala/com/sumologic/sumobot/plugins/BotPlugin.scala
src/main/scala/com/sumologic/sumobot/plugins/HttpClientWithTimeOut.scala
src/main/scala/com/sumologic/sumobot/plugins/jenkins/JenkinsJobClient.scala
src/main/scala/com/sumologic/sumobot/plugins/pagerduty/PagerDutyEventApi.scala
src/main/scala/com/sumologic/sumobot/plugins/pagerduty/PagerDutySchedulesManager.scala

Also fixed some deprecated stuff

Upgrade jenkins client

---

pom.xml
src/main/resources/com/sumologic/sumobot/http_frontend/index.html
src/main/resources/com/sumologic/sumobot/http_frontend/script.js
src/main/resources/com/sumologic/sumobot/http_frontend/style.css
src/main/scala/com/sumologic/sumobot/http_frontend/SumoBotHttpServer.scala

- Added CSS styling to sumobot-over-HTTP
- Page now has a proper layout
- Modified JavaScript to:
- properly display incoming and outcoming messages
- scroll to new messages as they arrive
- send message by pressing Enter (instead of clicking "Send" button)
New UI:

sumobot-over-HTTP: Add CSS styles

---

src/main/scala/com/sumologic/sumobot/plugins/advice/Advice.scala
src/main/scala/com/sumologic/sumobot/test/BotPluginTestKit.scala
src/test/scala/com/sumologic/sumobot/plugins/advice/AdviceTest.scala

- Fixes (ignored) test in Advice plugin (marked `TODO`)

Fix ignored test in Advice plugin

---

build.gradle
pom.xml
src/main/scala/com/sumologic/sumobot/plugins/BotPlugin.scala
src/main/scala/com/sumologic/sumobot/plugins/help/Help.scala
src/main/scala/com/sumologic/sumobot/plugins/pagerduty/PagerDutySchedulesManager.scala
src/test/scala/com/sumologic/sumobot/core/ReceptionistTest.scala

I recommend reviewing this PR commit by commit.

Make Sumo Bot buildable on Scala 2.12

---

src/main/scala/com/sumologic/sumobot/plugins/BotPlugin.scala
src/main/scala/com/sumologic/sumobot/plugins/help/Help.scala
src/main/scala/com/sumologic/sumobot/plugins/jenkins/Jenkins.scala
src/main/scala/com/sumologic/sumobot/plugins/system/System.scala

Add separate execution context for each BotPlugin.
Add timeout for response time.

Add isolation of responding for different plugins

---

CHANGELOG.md
build.gradle

Publicly releasing Sumobot 1.0.3 as:
`sumobot_2.11:1.0.3`
`sumobot_2.12:1.0.3`

Sumobot 1.0.3

---

README.md
build.gradle
gradle.properties
src/main/scala/com/sumologic/sumobot/core/HttpReceptionist.scala
src/test/scala/com/sumologic/sumobot/core/ReceptionistTest.scala
src/test/scala/com/sumologic/sumobot/core/model/ChannelTest.scala

Bumping to 0.2.9 of `slack-scala-client`

Bumping to 0.2.9

---

build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
src/test/scala/com/sumologic/sumobot/core/ReceptionistTest.scala

slack-scala-client upgraded to 0.2.14

slack-scala-client 0.2.14

---

build.gradle
gradle.properties

Manually upgrading chosen dependencies for no direct reason

Upgrading dependencies

---

src/main/scala/com/sumologic/sumobot/plugins/BotPlugin.scala

Adding a convenience method `channelForName()`

Adding channelForName() method

---

src/main/scala/com/sumologic/sumobot/core/Receptionist.scala
src/main/scala/com/sumologic/sumobot/core/model/Messages.scala

Adding support for sending images in threads.

OutgoingImage to be sent in thread

---

CHANGELOG.md
README.md
build.gradle

Sumobot 1.0.16

---

src/main/scala/com/sumologic/sumobot/core/Receptionist.scala
src/main/scala/com/sumologic/sumobot/core/model/Messages.scala
src/main/scala/com/sumologic/sumobot/plugins/BotPlugin.scala

Adding basic support for plugins to receive a notification of reactions/emoji.

Adding basic support for reactions

---

src/main/scala/com/sumologic/sumobot/plugins/BotPlugin.scala

Fix instantMessageChannel() - the IM channel 'user' property needs to be compared against user name, not the user object.

Update BotPlugin: add userByName search

---

src/main/scala/com/sumologic/sumobot/plugins/BotPlugin.scala
src/test/scala/com/sumologic/sumobot/plugins/BotPluginTest.scala

Add testing for userByName and instantMessageChannel.

Fix on fix - im.user stores userId, not user name.

---

build.gradle

Dropping jcenter repository

---

gradle.properties

Taking the latest patches for Scala 2.12 and 2.13:
- 2.12.15
- 2.13.8

Upgrading to Scala 2.12.15 and 2.13.8

---

build.gradle
src/main/scala/com/sumologic/sumobot/brain/S3Brain.scala
src/main/scala/com/sumologic/sumobot/core/config/ListOfConfigs.scala
src/main/scala/com/sumologic/sumobot/http_frontend/SumoBotHttpServerOptions.scala
src/main/scala/com/sumologic/sumobot/plugins/OperatorLimits.scala
src/main/scala/com/sumologic/sumobot/plugins/awssupport/AWSSupport.scala
src/main/scala/com/sumologic/sumobot/plugins/jenkins/JenkinsJobClient.scala
src/test/scala/com/sumologic/sumobot/brain/BlockingBrainTest.scala
src/test/scala/com/sumologic/sumobot/brain/S3BrainTest.scala
src/test/scala/com/sumologic/sumobot/core/PluginRegistryTest.scala
src/test/scala/com/sumologic/sumobot/http_frontend/HttpIncomingReceiverTest.scala
src/test/scala/com/sumologic/sumobot/http_frontend/HttpOutcomingSenderTest.scala
src/test/scala/com/sumologic/sumobot/http_frontend/RoutingHelperTest.scala
src/test/scala/com/sumologic/sumobot/http_frontend/SumoBotHttpServerTest.scala
src/test/scala/com/sumologic/sumobot/http_frontend/authentication/AuthenticatedServerTest.scala
src/test/scala/com/sumologic/sumobot/http_frontend/authentication/BasicAuthenticationTest.scala
src/test/scala/com/sumologic/sumobot/plugins/advice/AdviceTest.scala
src/test/scala/com/sumologic/sumobot/plugins/help/HelpTest.scala

Fixing some of Scala 2.13 warnings

---

build.gradle
src/main/scala/com/sumologic/sumobot/http_frontend/HttpIncomingReceiver.scala
src/main/scala/com/sumologic/sumobot/http_frontend/SumoBotHttpServer.scala
src/test/scala/com/sumologic/sumobot/http_frontend/RoutingHelperTest.scala
src/test/scala/com/sumologic/sumobot/http_frontend/SumoBotHttpServerTest.scala
src/test/scala/com/sumologic/sumobot/http_frontend/authentication/AuthenticatedServerTest.scala

... and all the related dependencies as a consequence (akka, akka-http, play)

Upgrade to slack-scala-client 0.3.1

---

src/main/scala/com/sumologic/sumobot/core/Receptionist.scala
src/main/scala/com/sumologic/sumobot/core/model/Messages.scala

channelId in ResponseInProgress

---

src/main/scala/com/sumologic/sumobot/plugins/pagerduty/PagerDuty.scala

Otherwise it might easily pollute the screen

Moving the response to "who is oncall" to thread

---

build.gradle

**What**:
Removing `goledzki` from the list of developers.
**Why**:
No longer part of the developing team.

Removing goledzki
